# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9d4b20ea-e049-4930-bd50-5028f1b6d3c1";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E0E0-2DC7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Автоматическое монтирование дополнительных дисков при загрузке
  fileSystems."/run/media/data" = {
    device = "/dev/disk/by-uuid/7b46fa4a-4886-4250-bff3-c52889aeeebc"; # sdb1 (ext4)
    fsType = "ext4";
    options = [ "defaults" "noatime" "x-systemd.automount" ]; # x-systemd.automount - монтирует при первом обращении
  };

  fileSystems."/run/media/windows" = {
    device = "/dev/disk/by-uuid/6CD0D1A9D0D17A32"; # nvme0n1p1 (NTFS)
    fsType = "ntfs-3g"; # Для NTFS лучше использовать ntfs-3g
    options = [ "defaults" "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "x-systemd.automount" ];
    # uid=1000 и gid=100 — дают права твоему пользователю (akane). Уточни id через `id akane`
  };

  fileSystems."/run/media/ntfs-test" = {
    device = "/dev/disk/by-uuid/F6A09F61A09F26E1"; # nvme0n1p1 (NTFS)
    fsType = "ntfs-3g"; # Для NTFS лучше использовать ntfs-3g
    options = [ "defaults" "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "x-systemd.automount" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}