# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e355aa1c-1c09-4c6f-96dc-fe3b92f5a1e6";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };
  fileSystems."/mnt/namana" =
    { device = "/dev/disk/by-uuid/043b339b-9073-480c-a65f-31a7cde5a83b";
      fsType = "ext4";
      options = ["noatime" "nodiratime" ];
    };

  # Автоматическое монтирование дополнительных дисков при загрузке
  fileSystems."/run/media/data" = {
    device = "/dev/disk/by-uuid/7b46fa4a-4886-4250-bff3-c52889aeeebc"; # sdb1 (ext4)
    fsType = "ext4";
    options = [ "defaults" "noatime" "x-systemd.automount" ]; # x-systemd.automount - монтирует при первом обращении
  };

  fileSystems."/run/media/windows" = {
    device = "/dev/disk/by-uuid/6CD0D1A9D0D17A32"; # nvme0n1p1 (NTFS)
    fsType = "ntfs-3g"; # Для NTFS лучше использовать ntfs-3g
    options = [ "defaults" "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "x-systemd.automount" ];
    # uid=1000 и gid=100 — дают права твоему пользователю (akane). Уточни id через `id akane`
  };

  fileSystems."/run/media/games" = {
    device = "/dev/disk/by-uuid/F6A09F61A09F26E1"; # nvme0n1p1 (NTFS)
    fsType = "ntfs-3g"; # Для NTFS лучше использовать ntfs-3g
    options = [ "defaults" "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "x-systemd.automount" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
